apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jinha6132/Park-argo
    targetRevision: main
    path: wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
