apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: wordpress
type: Opaque
stringData:
  # 워드프레스 DB 비밀번호. 기존 매니페스트에서 key 이름이 'password.txt'였으므로 동일하게 유지합니다.
  password.txt: "31605141"
